config/routes.rb
FishCms::Application.routes.draw do

  resources :categories

  resources :artworks

  resources :artists

  resources :awards

  resources :members do
    collection do
      post :sort
    end
  end

  resources :slides do
    collection do
      post :sort
    end
  end
  
  resources :pages  
  resources :categories do
    collection do
      post :sort
    end
  end 
  resources :links
  resources :uploads

  get "home/index"
  get "home/search"
  get "home/news"
  get "home/categories"
  get "admin/index"
  get "home/about"
  get "home/contactus"
  get "home/members"
  get "home/artists"
  get "home/artworks"
  match '/:pinyin', :to => 'artists#show'
  match 'admin',:to=>"admin/index"

  root :to => "home#index"
  
  resources :posts do
    collection do
      get :sta
      get :period
      get :wait_for_be_approved
      post :sort
    end

    post :approve, :on => :member
  end
  
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users, :path_prefix => 'my'
  resources :users

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessible :image, :link, :order, :title
  has_attached_file :image, 
    :url => "/images/slide/:id/:basename_:style.:extension",
    :path => ":rails_root/public/images/slide/:id/:basename_:style.:extension",
    :styles => { :content => "960x540>", :thumb => "150x85#" }
end

app/controllers/slides_controller.rb
#coding: utf-8
class SlidesController < ApplicationController
  load_and_authorize_resource
  layout "admin"
  # GET /slides
  # GET /slides.json
  def index
    @slides_grid = initialize_grid(Slide,:per_page => 10)
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
    @slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slide }
    end
  end

  # GET /slides/new
  # GET /slides/new.json
  def new
    @slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slide }
    end
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(params[:slide])

    respond_to do |format|
      if @slide.save
        format.html { redirect_to slides_url, notice: '幻灯片创建成功.' }
        format.json { render json: @slide, status: :created, location: @slide }
      else
        format.html { render action: "new" }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /slides/1
  # PUT /slides/1.json
  def update
    @slide = Slide.find(params[:id])

    respond_to do |format|
      if @slide.update_attributes(params[:slide])
        format.html { redirect_to slides_url, notice: '幻灯片修改成功.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to slides_url }
      format.json { head :no_content }
    end
  end
  
  def sort
    Slide.all.each do | w |
      w.position = params["item"].index(w.id.to_s)+1
      w.save
    end
    render :nothing => true
  end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
        <% @slide.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title,"标题" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link,"链接" %>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :image,"图片" %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "提交", :class => "btn btn-primary" %> 或者 <%= link_to '返回', members_path %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<%= content_for :base_sitemap do %>
  <ul class="breadcrumb">
    <li><a href="/admin/index">后台管理</a> <span class="divider">/</span></li>
    <li><%=link_to "首页幻灯片管理", slides_path  %><span class="divider">/</span></li>
    <li class="active">修改幻灯片 <%=@slide.title%></li>
  </ul>
<%end%>

<%= render 'form' %>

app/views/slides/index.html.erb
<%= content_for :base_sitemap do %>
  <ul class="breadcrumb">
    <li><a href="/admin/index">后台管理</a> <span class="divider">/</span></li>
    <li class="active">幻灯片管理</li>
  </ul>
<%end%>

<div class="tools">
  <a href="<%= slides_path %>" class="btn btn-info">查看所有</a>
  <a href="<%= new_slide_path %>" class="btn btn-success">新建</a>
</div>
<%= grid(@slides_grid) do |g|

  g.column :name => '标题', :attribute => 'title', filter: false,:html=>{:style=>"width:280px;"}

  g.column do |slide|   
    image_tag slide.image.url(:thumb)
  end


  g.column   do |slide|
    link_to('修改', edit_slide_path(slide))
  end

  g.column do |slide|
    link_to('删除', slide, method: :delete, data: { confirm: '你确定?' })
  end
end -%>

app/views/slides/new.html.erb
<%= content_for :base_sitemap do %>
  <ul class="breadcrumb">
    <li><a href="/admin/index">后台管理</a> <span class="divider">/</span></li>
    <li><%=link_to "首页幻灯片管理", slides_path  %><span class="divider">/</span></li>
    <li class="active">新增幻灯片</li>
  </ul>
<%end%>

<%= render 'form' %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @slide.title %>
</p>

<p>
  <b>Link:</b>
  <%= @slide.link %>
</p>

<p>
  <b>Image:</b>
  <%= @slide.image %>
</p>

<p>
  <b>Order:</b>
  <%= @slide.order %>
</p>


<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>