config/routes.rb
FishCms::Application.routes.draw do

  resources :categories

  resources :artworks

  resources :artists

  resources :awards

  resources :members do
    collection do
      post :sort
    end
  end

  resources :slides do
    collection do
      post :sort
    end
  end
  
  resources :pages  
  resources :categories do
    collection do
      post :sort
    end
  end 
  resources :links
  resources :uploads

  get "home/index"
  get "home/search"
  get "home/news"
  get "home/categories"
  get "admin/index"
  get "home/about"
  get "home/contactus"
  get "home/members"
  get "home/artists"
  get "home/artworks"
  match '/:pinyin', :to => 'artists#show'
  match 'admin',:to=>"admin/index"

  root :to => "home#index"
  
  resources :posts do
    collection do
      get :sta
      get :period
      get :wait_for_be_approved
      post :sort
    end

    post :approve, :on => :member
  end
  
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users, :path_prefix => 'my'
  resources :users

end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :avatar, :description, :year
  has_attached_file :avatar, 
    :url => "/images/awards/avatar/:id/:basename_:style.:extension",
    :path => ":rails_root/public/images/awards/avatar/:id/:basename_:style.:extension",
    :styles => { :medium => "820x600>", :thumb => "100x100>" }
end

app/controllers/awards_controller.rb
# coding: UTF-8
class AwardsController < ApplicationController
  layout "admin"
  
  def index
    @awards_grid = initialize_grid(Award,:per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @award = Award.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end
  
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end
  
  def edit
    @award = Award.find(params[:id])
  end
  
  def create
    @award = Award.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to(awards_path, :notice => 'Award 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end
  
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to(awards_path, :notice => 'Award 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end
  
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to(awards_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<div id="award" class="form">
<%= simple_form_for(@award, 
  :url => (@award.id.blank? ? awards_path : award_path(@award)) ) do |f| %>

  <div class="inputs">
  <%= f.input :year %>
  <%= f.input :description %>
  <%= f.input :avatar %>
  </div>
  <div class="actions">
    <%= f.submit "提交", :class => "btn btn-primary" %> 或者 <%= link_to '返回', awards_path %>
  </div>
<% end %>
</div>

app/views/awards/edit.html.erb
<%= content_for :sitemap do %>
<span class="current">修改</span>
<% end %>

<%= content_for :base_sitemap do %>
<ul class="breadcrumb">
  <li><a href="/admin/index">管理后台</a> <span class="divider">/</span></li>
  <li><a href="<%= awards_path %>">awards</a> <span class="divider">/</span></li>
  <li class="active">修改</li>
</ul>

<% end %>
<%= content_for :styles do %>
<% end %>

<%= render 'form' %>

app/views/awards/index.html.erb
<%= content_for :sitemap do %>
  <span class="current">列表</span>
<% end %>

<%= content_for :base_sitemap do %>
  <a href="<%= awards_path %>">awards</a> » 
<% end %>
<%= content_for :styles do %>
<% end %>

<div class="tools">
  <a href="<%= awards_path %>" class=btn btn-info">查看所有</a>
  <a href="<%= new_award_path %>" class="btn btn-success">新建</a>
</div>

<div id="awards">
  <%= grid(@awards_grid, :show_filters => false) do |g|
    g.column :name => '', :attribute => 'id',  filter: false
    g.column :name => 'year', :attribute => 'year'
    g.column :name => 'description', :attribute => 'description'
    
    g.column do |a|   
      image_tag a.avatar.url(:thumb)
    end
    
    g.column :name => '创建时间', :attribute => 'created_at'
    g.column :name => '操作' do |c|
      raw "#{link_to '修改', edit_award_path(c.id)}
    #{link_to '删除', award_path(c.id), :method => :delete, :confirm => '确定要删除吗?'}"
    end
  end %>
</div>

app/views/awards/new.html.erb
<%= content_for :sitemap do %>
<span class="current">新建</span>
<% end %>

<%= content_for :base_sitemap do %>
<ul class="breadcrumb">
  <li><a href="/admin/index">管理后台</a> <span class="divider">/</span></li>
  <li><a href="<%= awards_path %>">awards</a> <span class="divider">/</span></li>
  <li class="active">新建</li>
</ul>
<% end %>
<%= content_for :styles do %>
<% end %>

<%= render 'form' %>

app/views/awards/show.html.erb
<%= content_for :sitemap do %>
<span class="current">查看</span>
<% end %>

<%= content_for :base_sitemap do %>
<ul class="breadcrumb">
  <li><a href="/admin/index">管理后台</a> <span class="divider">/</span></li>
  <li><a href="<%= awards_path %>">awards</a> <span class="divider">/</span></li>
  <li class="active">查看</li>
</ul>
<% end %>
<%= content_for :styles do %>
<% end %>

<div class="tools">
  <%= link_to '修改', edit_award_path(@award), :class => "btn small success" %>
  <%= link_to '返回', awards_path, :class => "btn small" %>
</div>
<div id="award">
      <p>
      <b>Year:</b>
      <%= @award.year %>
    </p>
      <p>
      <b>Description:</b>
      <%= @award.description %>
    </p>
      <p>
      <b>Avatar:</b>
      <%= @award.avatar %>
    </p>
  </div>